model:
  name: omniASR_CTC_300M_v2
  path: null
  family: wav2vec2_asr
  arch: null
  config_overrides: null
  dtype: float32
  mmap: false
  compile: false
  compile_options:
    fullgraph: false
    dynamic: false
    mode: default
    backend: inductor
    backend_options: null
pretrained_encoder:
  name: ''
  path: null
  family: wav2vec2_ssl
  arch: null
  config_overrides: null
  dtype: float32
  mmap: false
  compile: false
  compile_options:
    fullgraph: false
    dynamic: false
    mode: default
    backend: inductor
    backend_options: null
dataset:
  name: regspeech12
  family: null
  config_overrides: null
  train_split: train
  valid_split: valid
  storage_mode: MANIFEST
  task_mode: ASR
  manifest_storage_config:
    sync_batches: true
    sync_mode: UNTIL_FIRST
    read_text: true
    cached_fd_count: 1000
  mixture_parquet_storage_config:
    sync_batches: true
    sync_mode: UNTIL_FIRST
    fragment_streaming:
      parquet_path: ''
      filesystem: null
      name: null
      weight: 1.0
      partition_filters: null
      limit:
        fraction_of_files: null
        nb_files: null
        nb_fragments: null
        nb_rows: null
      split_to_row_groups: true
      seed: 2
      fragment_shuffle_window: 0
      files_circular_shift: false
      nb_epochs: null
    fragment_loading:
      columns: {}
      rename_columns: true
      add_fragment_traces: false
      drop_null: false
      min_batch_size: 1
      filters: null
      non_deterministic_read: false
      use_threads: false
      nb_prefetch: 1
      num_parallel_fragments: 1
      cache: true
      cache_dir: null
    dataset_summary_path: null
    beta_corpus: null
    beta_language: null
    pa_cpu_count: 20
    max_workers: 30
    split_column: split
    num_prefetch: 1
    parquet_path_name: _parquet_path
    sampling_seed: 261
  asr_task_config:
    min_audio_len: 16000
    max_audio_len: 480000
    batching_strategy: LENGTH
    batch_size: 8
    num_seqs_multiple_of: 8
    max_num_elements: 1000000
    max_bucket_size: null
    drop_remainder: false
    filter_long_text_threshold: null
    remove_unknown: false
    min_samples_per_char: 160
    normalize_audio: true
    use_fbank: false
    spec_aug_p: null
    spec_aug_freq_mask_param: 80
    spec_aug_time_mask_param: 80
    unified_audio_feature_keys: true
    example_shuffle_window: 1000
    batch_shuffle_window: 1000
    npc: 10
    seed: 2
    no_padding: false
    max_num_batches: null
    num_prefetch: 4
tokenizer:
  name: omniASR_tokenizer_written_v2
  path: null
  family: null
  config_overrides: null
gang:
  tensor_parallel_size: 1
  timeout: 15
  high_priority: true
trainer:
  data_parallelism: ddp
  fsdp:
    version: v2
    granularity: layer
    hybrid: false
    reshard_after_forward: true
    fp32_reduce: true
  mixed_precision:
    mode: static
    dtype: bfloat16
  grad_accumulation:
    num_batches: 8
    no_sync: false
  activation_checkpointing:
    mode: off
    every_nth_layer: 1
  max_grad_norm: null
  fp16_loss_scale:
  - 128.0
  - 0.0001
  gc_every_n_steps: 1000
  grad_check: false
  anomaly_detection: false
  freeze_encoder_for_n_steps: 0
optimizer:
  name: adamw
  config:
    lr: 5e-05
    betas:
    - 0.9
    - 0.98
    eps: 1e-08
    weight_decay: 0.01
    amsgrad: false
    maximize: false
    capturable: false
    differentiable: false
    impl: auto
    groups: []
lr_scheduler:
  name: tri_stage
  config:
    stage_ratio:
    - 0.1
    - 0.4
    - 0.5
    start_lr_scale: 0.01
    final_lr_scale: 0.05
regime:
  num_steps: 10000
  num_data_epochs: null
  validate_at_start: false
  validate_after_n_steps: 500
  validate_every_n_steps: 1000
  validate_after_n_data_epochs: 0
  validate_every_n_data_epochs: null
  score_metric: wer
  checkpoint_after_n_steps: 0
  checkpoint_every_n_steps: 2000
  checkpoint_after_n_data_epochs: 0
  checkpoint_every_n_data_epochs: null
  save_model_only: false
  export_hugging_face: false
  keep_last_n_checkpoints: null
  keep_best_n_checkpoints: null
  keep_checkpoint_every_n_steps: null
  publish_metrics_after_n_steps: 0
  publish_metrics_every_n_steps: 100
  publish_metrics_after_n_data_epochs: 0
  publish_metrics_every_n_data_epochs: null
common:
  torch:
    num_threads: null
    allow_tf32: true
    fp16_reduced_precision: true
    bf16_reduced_precision: true
    default_sdpa: torch
    compiled_region_activation_memory_budget: 1.0
  metric_recorders:
    tensorboard:
      enabled: true
    wandb:
      enabled: false
      entity: null
      project: null
      run_id: persistent
      run_name: null
      group: null
      job_type: null
      resume_mode: null
  profilers:
    torch:
      enabled: false
      skip_n_steps: 4
      wait_n_steps: 0
      num_warmup_steps: 1
      num_active_steps: 4
      repeat: 1
  assets:
    extra_paths: []
    prev_checkpoint_dir: null
  seed: 2
  debug: false
  cluster: auto
  no_sweep_dir: false
  sweep_format: ws_{world_size}.{hash}
